// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABKI43F64GGz7GdfeJMlZUt_XplJID1m0',
    appId: '1:929424962414:web:9bae752dda60fb73ad477f',
    messagingSenderId: '929424962414',
    projectId: 'ocr-flutter-3458a',
    authDomain: 'ocr-flutter-3458a.firebaseapp.com',
    storageBucket: 'ocr-flutter-3458a.appspot.com',
    measurementId: 'G-R9MHXLMHNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQH_9ZiCCpzOBbq5e2m5sQ-oFdKNlcx0',
    appId: '1:929424962414:android:070ac4bf3563014dad477f',
    messagingSenderId: '929424962414',
    projectId: 'ocr-flutter-3458a',
    storageBucket: 'ocr-flutter-3458a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGnfXGSe7b4V3AFNrEyeOWpVVGZ9_y8iI',
    appId: '1:929424962414:ios:25b4280a01ead44aad477f',
    messagingSenderId: '929424962414',
    projectId: 'ocr-flutter-3458a',
    storageBucket: 'ocr-flutter-3458a.appspot.com',
    iosBundleId: 'com.example.ocrFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGnfXGSe7b4V3AFNrEyeOWpVVGZ9_y8iI',
    appId: '1:929424962414:ios:25b4280a01ead44aad477f',
    messagingSenderId: '929424962414',
    projectId: 'ocr-flutter-3458a',
    storageBucket: 'ocr-flutter-3458a.appspot.com',
    iosBundleId: 'com.example.ocrFlutterProject',
  );
}
